import type { Meta, StoryObj } from '@storybook/react';
import ProductList from './ProductList';
import { Product } from '../../types/product';
import images from '../../assets/images/jacket.jpg';

const Products: Product[] = [
  {
    title: 'title 1',
    price: 14,
    images: [images],
    colors: [],
    sizes: ['blue', 'whilte'],
    description: 'description 1',
    stock: 45,
    rate: 31,
    numberRating: 2,
    category: '1',
    id: 1,
  },
  {
    title: 'title 2',
    price: 61,
    images: [images],
    colors: [],
    sizes: ['blue', 'whilte'],
    description: 'description 2',
    stock: 83,
    rate: 99,
    numberRating: 4,
    category: '2',
    id: 2,
  },
  {
    title: 'title 3',
    price: 40,
    images: [images],
    colors: [],
    sizes: [],
    description: 'description 3',
    stock: 6,
    rate: 73,
    numberRating: 3,
    category: 'category 3',
    id: 3,
  },
  {
    title: 'title 4',
    price: 3,
    images: [images],
    colors: [],
    sizes: [],
    description: 'description 4',
    stock: 43,
    rate: 78,
    numberRating: 4,
    category: '1',
    id: 4,
  },
  {
    title: 'title 5',
    price: 63,
    images: [images],
    colors: [],
    sizes: [],
    description: 'description 5',
    stock: 87,
    rate: 37,
    numberRating: 4,
    category: '2',
    id: 5,
  },
  {
    title: 'title 5',
    price: 63,
    images: [images],
    colors: [],
    sizes: [],
    description: 'description 5',
    stock: 87,
    rate: 37,
    numberRating: 4,
    category: '2',
    id: 6,
  },
  {
    title: 'title 5',
    price: 63,
    images: [images],
    colors: [],
    sizes: [],
    description: 'description 5',
    stock: 87,
    rate: 37,
    numberRating: 4,
    category: '2',
    id: 7,
  },
  {
    title: 'title 5',
    price: 63,
    images: [images],
    colors: [],
    sizes: [],
    description: 'description 5',
    stock: 87,
    rate: 37,
    numberRating: 4,
    category: '2',
    id: 8,
  },
];
export default {
  component: ProductList,
  title: 'Components/ProductList',
} as Meta;

type Story = StoryObj<typeof ProductList>;

export const Default: Story = {
  args: { products: Products },
};
